export const UPDATE_GPS_POSITION = "UPDATE_GPS_POSITION";
export const UPDATE_ERRORS = "UPDATE_ERRORS";
export const DELETE_ERRORS = "DELETE_ERRORS";
export const UPDATE_USER_ACTION = "UPDATE_USER_ACTION";
export const UPDATE_NOTES_IN_BOUNDS = "UPDATE_NOTES_IN_BOUNDS";
export const UPDATE_CENTER_MAP = "UPDATE_CENTER_MAP";
export const UPDATE_MAP_BOUNDS = "UPDATE_MAP_BOUNDS";
export const UPDATE_TIMER = "UPDATE_TIMER";


