export const UPDATE_GPS_POSITION = "UPDATE_GPS_POSITION";
export const UPDATE_USER_ACTION = "UPDATE_USER_ACTION";
export const UPDATE_NOTES_IN_BOUNDS = "UPDATE_NOTES_IN_BOUNDS";
export const UPDATE_GOOGLE_MAP_BOUNDS = "UPDATE_GOOGLE_MAP_BOUNDS";


