export const UPDATE_GPS_POSITION = "UPDATE_GPS_POSITION";
export const UPDATE_ERRORS = "UPDATE_ERRORS";
export const UPDATE_USER_ACTION = "UPDATE_USER_ACTION";
export const UPDATE_NOTES_IN_PROXIMITY = "UPDATE_NOTES_IN_PROXIMITY";


